apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "boteventtemplateapi.fullname" . }}-deployment
  labels:
    app: {{ template "boteventtemplateapi.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "boteventtemplateapi.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "boteventtemplateapi.name" . }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.imagePullSecretName }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.probes.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- end }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.environments.AspNetCore }}
            - name: BasePath
              value: {{ .Values.environments.BasePath }}
            - name: DefaultConnection
              valueFrom:
               secretKeyRef:
                name: {{ .Values.secretEventmanagement.Name }}
                key: {{ .Values.secretEventmanagement.Key }}
          args: ["$(ASPNETCORE_ENVIRONMENT) $(DefaultConnection) $(BasePath)"]                
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources: {}