apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "boteventmanagementui.fullname" . }}-deployment
  labels:
    app: {{ template "boteventmanagementui.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "boteventmanagementui.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "boteventmanagementui.name" . }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.imagePullSecretName }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: config
            mountPath: {{ .Values.appSettings.path }}
            subPath: {{ .Values.appSettings.subPath }}
          {{- if .Values.probes.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- end }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.environments.AspNetCore }}
            - name: BasePath
              value: {{ .Values.environments.BasePath }}
            - name: EventManagerApiUrl
              value: {{ .Values.environments.EventManagerApiUrl }}
            - name: DefaultConnection
              valueFrom:
               secretKeyRef:
                name: {{ .Values.secretEventmanagement.Name }}
                key: {{ .Values.secretEventmanagement.Key }}
          args: ["$(ASPNETCORE_ENVIRONMENT) $(BasePath) $(EventManagerApiUrl) $(DefaultConnection)"]
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources: {}
      volumes: 
      - name: config
        configMap:
          name: {{ .Values.appSettings.configMap }}