apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  {{ template "boteventmanagementui.fullname" . }}-ingress
  labels:
    app: {{ template "boteventmanagementui.name" . }}
    chart: {{ template "boteventmanagementui.chart" . }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.hostName }}
      http:
        paths:
          - backend:
              serviceName: {{ .Values.ingress.serviceName }}
              servicePort: http
            path: {{ .Values.ingress.path }}