apiVersion: v1
kind: Service
metadata:
  name: {{ template "boteventmanagementui.fullname" . }}-service
  labels:
    app: {{ template "boteventmanagementui.name" . }}
    chart: {{ template "boteventmanagementui.chart" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "boteventmanagementui.name" . }}