apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: kube-system
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: tulio.mamute@hotmail.com
    privateKeySecretRef:
      name: acme-crt-secret
    http01: {}