// <auto-generated />
using System;
using BotEventManagement.Services.Model.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BotEventManagement.Services.Migrations
{
    [DbContext(typeof(BotEventManagementContext))]
    partial class BotEventManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BotEventManagement.Services.Model.Database.Event", b =>
                {
                    b.Property<string>("EventId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EventDescription");

                    b.Property<DateTime>("EventEndDate");

                    b.Property<string>("EventName");

                    b.Property<DateTime>("EventStartDate");

                    b.HasKey("EventId");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("BotEventManagement.Services.Model.Database.Event", b =>
                {
                    b.OwnsOne("BotEventManagement.Services.Model.Database.Address", "Address", b1 =>
                        {
                            b1.Property<string>("EventId");

                            b1.Property<double>("Latitude")
                                .HasColumnName("Latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnName("Longitude");

                            b1.Property<string>("Street")
                                .HasColumnName("Street");

                            b1.ToTable("Event");

                            b1.HasOne("BotEventManagement.Services.Model.Database.Event")
                                .WithOne("Address")
                                .HasForeignKey("BotEventManagement.Services.Model.Database.Address", "EventId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
