kind: List
metadata: {}
apiVersion: v1
items:

- apiVersion: v1
  kind: Service
  metadata:
    name: boteventmanagement-api-service
    labels:
      version: test
  spec:
    selector:
        app: boteventmanagement-api
    ports:
    - port: 80
    type: LoadBalancer

- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    name: boteventmanagement-api-deployment
  spec:
    replicas: 2
    strategy: {}
    template:
        metadata:
          labels:
            app: boteventmanagement-api
        spec:
          containers:
          - name: boteventmanagement-api
            image: tuliorezende/boteventmanagement-api
            env:
                - name: ASPNETCORE_ENVIRONMENT
                  value: Production
                - name: DefaultConnection
                  valueFrom:
                   secretKeyRef:
                    name: secret-eventmanagement
                    key: DEFAULTCONNECTION
            args: ["$(ASPNETCORE_ENVIRONMENT) $(DefaultConnection)"]
            ports:
            - containerPort: 80
            resources: {}
  status: {}